tables = {
    "Hricotransa": [
        "Record_id", 
        "FONDO", 
        "TIPO", 
        "FECHA", 
        "CLIENTE", 
        "RED", 
        "OFICINA", 
        "FIDEICOMISO", 
        "comprobante", 
        "VALOR", 
        "unidades", 
        "concta", 
        "USUARIO", 
        "Retencion", 
        "Tipo_de_Aporte", 
        "CODIGOBPM", 
        "HORA", 
        "FechaPago", 
        "SwImpuesto", 
        "CodigoSistema", 
        "Maquina", 
        "IP", 
        "SaldoDespuesMovimiento"
    ],
    "Tbl_sif_hrico_saldodisponible": [
        "HSDI_IN_ID", 
        "HSDI_IN_FONDO", 
        "HSDI_IN_IDENCARGO", 
        "HSDI_DT_FECHA", 
        "HSDI_DE_RTEXAPLICAR", 
        "HSDI_DE_RETENCIONDIA", 
        "HSDI_DE_SALDO_DISPONIBLE"
    ],
    "Tbl_Log": [
        "Id", 
        "Fecha", 
        "IdProceso", 
        "Usuario", 
        "Ip", 
        "Maquina", 
        "Descripcion", 
        "Objeto", 
        "ProcesoExitoso", 
        "IDObjeto", 
        "EstadoAnteriorObjeto"
    ]
}